#!/bin/bash

# print standard input to standard output
# discarding all lines before the first line matching
# the string giving as the first argument

if [[ ! $1 ]]; then
    echo "Need first argument " >2&
    exit 1
fi

found=""

# read upto first mactch
while read -r || [[ $REPLY ]]; do
    if [[ ! found ]]; then
        if [[ REPLY =~ $1 ]]; then
            found='yes'
        else
            continue
        fi
    fi
    echo $REPLY
done

exit 0

